/*
 * This file is generated by jOOQ.
 */
package com.revolut.challenge.jooq;


import com.revolut.challenge.jooq.tables.AccountTransaction;
import com.revolut.challenge.jooq.tables.FinancialAccount;
import com.revolut.challenge.jooq.tables.Transfer;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index IDX_ACCOUNT_NUMBER = Indexes0.IDX_ACCOUNT_NUMBER;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", AccountTransaction.ACCOUNT_TRANSACTION, new OrderField[] { AccountTransaction.ACCOUNT_TRANSACTION.ID }, true);
        public static Index IDX_ACCOUNT_NUMBER = Internal.createIndex("IDX_ACCOUNT_NUMBER", FinancialAccount.FINANCIAL_ACCOUNT, new OrderField[] { FinancialAccount.FINANCIAL_ACCOUNT.ACCOUNT_NUMBER }, true);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", FinancialAccount.FINANCIAL_ACCOUNT, new OrderField[] { FinancialAccount.FINANCIAL_ACCOUNT.ID }, true);
        public static Index PRIMARY_KEY_7 = Internal.createIndex("PRIMARY_KEY_7", Transfer.TRANSFER, new OrderField[] { Transfer.TRANSFER.ID }, true);
    }
}
