/*
 * This file is generated by jOOQ.
 */
package com.revolut.challenge.jooq;


import com.revolut.challenge.jooq.tables.AccountTransaction;
import com.revolut.challenge.jooq.tables.FinancialAccount;
import com.revolut.challenge.jooq.tables.Transfer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1970191567;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNT_TRANSACTION</code>.
     */
    public final AccountTransaction ACCOUNT_TRANSACTION = com.revolut.challenge.jooq.tables.AccountTransaction.ACCOUNT_TRANSACTION;

    /**
     * The table <code>PUBLIC.FINANCIAL_ACCOUNT</code>.
     */
    public final FinancialAccount FINANCIAL_ACCOUNT = com.revolut.challenge.jooq.tables.FinancialAccount.FINANCIAL_ACCOUNT;

    /**
     * The table <code>PUBLIC.TRANSFER</code>.
     */
    public final Transfer TRANSFER = com.revolut.challenge.jooq.tables.Transfer.TRANSFER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AccountTransaction.ACCOUNT_TRANSACTION,
            FinancialAccount.FINANCIAL_ACCOUNT,
            Transfer.TRANSFER);
    }
}
