/*
 * This file is generated by jOOQ.
 */
package com.revolut.challenge.jooq;


import com.revolut.challenge.jooq.tables.AccountTransaction;
import com.revolut.challenge.jooq.tables.FinancialAccount;
import com.revolut.challenge.jooq.tables.Transfer;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT_TRANSACTION</code>.
     */
    public static final AccountTransaction ACCOUNT_TRANSACTION = AccountTransaction.ACCOUNT_TRANSACTION;

    /**
     * The table <code>PUBLIC.FINANCIAL_ACCOUNT</code>.
     */
    public static final FinancialAccount FINANCIAL_ACCOUNT = FinancialAccount.FINANCIAL_ACCOUNT;

    /**
     * The table <code>PUBLIC.TRANSFER</code>.
     */
    public static final Transfer TRANSFER = Transfer.TRANSFER;
}
