/*
 * This file is generated by jOOQ.
 */
package com.revolut.challenge.jooq.tables.records;


import com.revolut.challenge.jooq.tables.Transfer;
import com.revolut.challenge.model.enumeration.TransferStatusType;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferRecord extends UpdatableRecordImpl<TransferRecord> implements Record5<Long, TransferStatusType, Long, Long, LocalDateTime> {

    private static final long serialVersionUID = 1523563182;

    /**
     * Setter for <code>PUBLIC.TRANSFER.ID</code>.
     */
    public TransferRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.TRANSFER_STATUS_TYPE</code>.
     */
    public TransferRecord setTransferStatusType(TransferStatusType value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.TRANSFER_STATUS_TYPE</code>.
     */
    public TransferStatusType getTransferStatusType() {
        return (TransferStatusType) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.FROM_ACCOUNT</code>.
     */
    public TransferRecord setFromAccount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.FROM_ACCOUNT</code>.
     */
    public Long getFromAccount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.TO_ACCOUNT</code>.
     */
    public TransferRecord setToAccount(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.TO_ACCOUNT</code>.
     */
    public Long getToAccount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFER.CREATE_DATETIME</code>.
     */
    public TransferRecord setCreateDatetime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.TRANSFER.CREATE_DATETIME</code>.
     */
    public LocalDateTime getCreateDatetime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, TransferStatusType, Long, Long, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, TransferStatusType, Long, Long, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Transfer.TRANSFER.ID;
    }

    @Override
    public Field<TransferStatusType> field2() {
        return Transfer.TRANSFER.TRANSFER_STATUS_TYPE;
    }

    @Override
    public Field<Long> field3() {
        return Transfer.TRANSFER.FROM_ACCOUNT;
    }

    @Override
    public Field<Long> field4() {
        return Transfer.TRANSFER.TO_ACCOUNT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Transfer.TRANSFER.CREATE_DATETIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public TransferStatusType component2() {
        return getTransferStatusType();
    }

    @Override
    public Long component3() {
        return getFromAccount();
    }

    @Override
    public Long component4() {
        return getToAccount();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDatetime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public TransferStatusType value2() {
        return getTransferStatusType();
    }

    @Override
    public Long value3() {
        return getFromAccount();
    }

    @Override
    public Long value4() {
        return getToAccount();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDatetime();
    }

    @Override
    public TransferRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TransferRecord value2(TransferStatusType value) {
        setTransferStatusType(value);
        return this;
    }

    @Override
    public TransferRecord value3(Long value) {
        setFromAccount(value);
        return this;
    }

    @Override
    public TransferRecord value4(Long value) {
        setToAccount(value);
        return this;
    }

    @Override
    public TransferRecord value5(LocalDateTime value) {
        setCreateDatetime(value);
        return this;
    }

    @Override
    public TransferRecord values(Long value1, TransferStatusType value2, Long value3, Long value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferRecord
     */
    public TransferRecord() {
        super(Transfer.TRANSFER);
    }

    /**
     * Create a detached, initialised TransferRecord
     */
    public TransferRecord(Long id, TransferStatusType transferStatusType, Long fromAccount, Long toAccount, LocalDateTime createDatetime) {
        super(Transfer.TRANSFER);

        set(0, id);
        set(1, transferStatusType);
        set(2, fromAccount);
        set(3, toAccount);
        set(4, createDatetime);
    }
}
